import { AuditLog, ComplianceStandard, GlobalThreatMetrics, SimulationScenario } from '../types';

export const INITIAL_GLOBAL_METRICS: GlobalThreatMetrics = {
  threatLevel: 'HIGH',
  overallThreatScore: 78,
  anomaliesDetected24h: 17,
  totalAtRiskAmount: 89840000, // ₹8.98 Cr
  quarantinedAmount: 62780000, // ₹6.28 Cr
  modelAccuracyPercent: 98.4,
  avgResponseTimeSec: 1.4,
  activeThreatVectorsCount: 6,
  mitigationRatePercent: 94.2,
  budgetRunRateVariance: 8.4,
};

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log_9921',
    timestamp: '2026-04-02T10:14:22Z',
    userId: 'usr_admin_01',
    userName: 'SENTINEL Automated Watchdog',
    userRole: 'ADMIN',
    action: 'AUTO_QUARANTINE_EXECUTED',
    targetType: 'TRANSACTION',
    targetId: 'TXN-2026-0402-99481',
    details: 'Intercepted ₹4.85 Crore offshore wire matching regulatory watchlist rule RL-SAN-006.',
    ipAddress: '10.240.12.88 (Internal Core)',
    immutableHash: '0x8f2a1b9c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a',
    status: 'CRITICAL',
  },
  {
    id: 'log_9920',
    timestamp: '2026-04-02T09:45:10Z',
    userId: 'usr_finance_02',
    userName: 'Rajesh Malhotra',
    userRole: 'FINANCE_OFFICER',
    action: 'FORENSIC_TRIAGE_NOTE_RECORDED',
    targetType: 'TRANSACTION',
    targetId: 'TXN-2026-0402-99480',
    details: 'Initiated contact with VP Eng regarding Cygnus Advisory ₹49.50 Lakh smurfing pattern alert.',
    ipAddress: '192.168.4.112 (VPN-IN-WEST)',
    immutableHash: '0x7e1a0b8c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0b',
    status: 'WARNING',
  },
  {
    id: 'log_9919',
    timestamp: '2026-04-02T08:30:00Z',
    userId: 'usr_admin_01',
    userName: 'Dr. Elena Vance',
    userRole: 'ADMIN',
    action: 'RULE_THRESHOLD_MODIFIED',
    targetType: 'RULE',
    targetId: 'RL-ENT-001',
    details: 'Adjusted Unverified Entity heuristic sensitivity threshold from 0.70 to 0.75.',
    ipAddress: '172.16.80.14 (HQ Secure Enclave)',
    immutableHash: '0x6d0e9f7a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e',
    status: 'SUCCESS',
  },
  {
    id: 'log_9918',
    timestamp: '2026-04-02T03:41:00Z',
    userId: 'usr_admin_01',
    userName: 'SENTINEL Off-Hours Watchdog',
    userRole: 'ADMIN',
    action: 'OFF_HOURS_TRANSFER_HELD',
    targetType: 'TRANSACTION',
    targetId: 'TXN-2026-0402-99478',
    details: 'Quarantined ₹1.43 Crore RTGS initiated at 03:41 IST with modified address profile.',
    ipAddress: '10.240.12.90 (Internal Core)',
    immutableHash: '0x5c9d8e6a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e',
    status: 'CRITICAL',
  },
  {
    id: 'log_9917',
    timestamp: '2026-04-01T22:15:40Z',
    userId: 'usr_finance_02',
    userName: 'Rajesh Malhotra',
    userRole: 'FINANCE_OFFICER',
    action: 'BUDGET_ADJUSTMENT_SIMULATED',
    targetType: 'BUDGET',
    targetId: 'ENG-01',
    details: 'Ran Monte Carlo simulation evaluating +15% GPU compute cost surge on Q2 FY 2026–27 burn rate.',
    ipAddress: '192.168.4.112 (VPN-IN-WEST)',
    immutableHash: '0x4b8c7d5a0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d',
    status: 'SUCCESS',
  },
  {
    id: 'log_9916',
    timestamp: '2026-04-01T18:00:12Z',
    userId: 'usr_dept_03',
    userName: 'Priya Sharma',
    userRole: 'DEPARTMENT_HEAD',
    action: 'EXPENSE_AUTHORIZED',
    targetType: 'TRANSACTION',
    targetId: 'TXN-2026-0331-99474',
    details: 'Authorized QuantumAI Research Systems quarterly data licensing invoice of ₹98,00,000.',
    ipAddress: '192.168.10.45 (HQ Tech Enclave)',
    immutableHash: '0x3a7b6c4a9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d',
    status: 'SUCCESS',
  },
];

export const INITIAL_SIMULATION_SCENARIOS: SimulationScenario[] = [
  {
    id: 'scen_macro_shock',
    name: 'Macro Inflation & Supply Squeeze (FY 2026–27)',
    description: 'Evaluates enterprise liquidity impact under +5.2% annualized inflation combined with a 15% surge in SaaS tooling and GPU hardware procurement costs.',
    inflationRateShock: 5.2,
    supplyChainDisruption: 15.0,
    headcountGrowth: 8.0,
    fxVolatilityShock: 6.5,
    contingencyBufferPercent: 12.0,
    projectedDeficit: 24500000, // ₹2.45 Cr
    projectedTotalSpend: 454500000, // ₹45.45 Cr
    confidenceScore: 92.4,
  },
  {
    id: 'scen_headcount_scale',
    name: 'R&D Headcount Scaling Expansion',
    description: 'Simulates 25% technical headcount surge in Engineering and AI research teams with accelerated compute consumption in FY 2026–27.',
    inflationRateShock: 3.1,
    supplyChainDisruption: 5.0,
    headcountGrowth: 25.0,
    fxVolatilityShock: 2.0,
    contingencyBufferPercent: 8.0,
    projectedDeficit: 38200000, // ₹3.82 Cr
    projectedTotalSpend: 468200000, // ₹46.82 Cr
    confidenceScore: 89.1,
  },
  {
    id: 'scen_austerity_freeze',
    name: 'Conservative Treasury Defense & Capital Preservation',
    description: 'Models immediate 15% budget clawback across discretionary marketing media, executive travel, and non-core SaaS subscriptions.',
    inflationRateShock: 2.5,
    supplyChainDisruption: 0.0,
    headcountGrowth: 0.0,
    fxVolatilityShock: 3.0,
    contingencyBufferPercent: 15.0,
    projectedDeficit: -12000000, // surplus ₹1.2 Cr
    projectedTotalSpend: 418000000, // ₹41.80 Cr
    confidenceScore: 95.8,
  },
];

export const INITIAL_COMPLIANCE_STANDARDS: ComplianceStandard[] = [
  {
    id: 'std_companies_act_ifc',
    name: 'Companies Act 2013 - Internal Financial Controls (IFC)',
    code: 'IFC-COMP-2013',
    standardType: 'COMPANIES_ACT_IFC',
    complianceScore: 96.2,
    status: 'COMPLIANT',
    totalControls: 48,
    passedControls: 46,
    failingControls: 2,
    lastAuditDate: '2026-03-15',
    leadAuditor: 'Corporate Statutory Assurance Committee',
    findings: [
      {
        id: 'fnd_ifc_01',
        controlId: 'CTRL-IFC-4.12',
        title: 'Single-Signatory Threshold Bypass Watch',
        severity: 'MEDIUM',
        description: 'Detected instances where sequential invoices were split below the ₹50 Lakh dual-signatory requirement (Smurfing flags).',
        remediation: 'Automated Sentinel rule RL-SMF-003 enforced to quarantine aggregate split invoices across 48h windows.',
      },
      {
        id: 'fnd_ifc_02',
        controlId: 'CTRL-IFC-8.04',
        title: 'Beneficiary Bank Detail Alteration Verification Lag',
        severity: 'LOW',
        description: 'Vendor bank account alterations previously permitted a 24-hour verification window without mandatory dual-key cryptographic lock.',
        remediation: 'Enforced instant 72-hour quarantine on all transfers to modified bank routing accounts.',
      },
    ],
  },
  {
    id: 'std_iso_27001',
    name: 'ISO/IEC 27001:2022 ISMS Financial Data Security',
    code: 'ISO-27001-ISMS',
    standardType: 'ISO_27001',
    complianceScore: 98.8,
    status: 'COMPLIANT',
    totalControls: 93,
    passedControls: 92,
    failingControls: 1,
    lastAuditDate: '2026-02-20',
    leadAuditor: 'BSI Global Assurance Services',
    findings: [
      {
        id: 'fnd_iso_01',
        controlId: 'A.12.1.2',
        title: 'Off-Hours Treasury Telemetry Logging',
        severity: 'LOW',
        description: 'Transfer origin IP addresses required mandatory hardware token multi-factor validation during off-hours cycles.',
        remediation: 'Configured Sentinel Rule RL-OFH-004 to require hardware WebAuthn challenge.',
      },
    ],
  },
  {
    id: 'std_sox_404',
    name: 'SOX Section 404 - Corporate Financial Reporting Controls',
    code: 'SOX-404-FIN',
    standardType: 'SOX_404',
    complianceScore: 95.4,
    status: 'COMPLIANT',
    totalControls: 52,
    passedControls: 50,
    failingControls: 2,
    lastAuditDate: '2026-03-01',
    leadAuditor: 'Statutory Independent Audit Partner',
    findings: [
      {
        id: 'fnd_sox_01',
        controlId: 'SOX-ITGC-09',
        title: 'Automated Quarantine Override Audit Trail',
        severity: 'MEDIUM',
        description: 'Manual overrides of Sentinel automated holds must be cryptographically co-signed by two authorized officers.',
        remediation: 'Multi-officer quorum verification enabled on Sentinel treasury gateway.',
      },
    ],
  },
];
