import { AnomalyRule } from '../types';

export const INITIAL_RULES: AnomalyRule[] = [
  {
    id: 'rule_phantom_vendor_01',
    name: 'Unverified Shell / Non-Standard Entity Detection',
    code: 'RL-ENT-001',
    category: 'PHANTOM_VENDOR',
    severity: 'CRITICAL',
    threshold: 'Unverified Likelihood > 75% AND Outbound Volume > ₹50,00,000 within 30 days',
    metric: 'EntityVerificationScore',
    action: 'AUTO_QUARANTINE',
    enabled: true,
    triggerCount24h: 3,
    lastTriggered: '2026-04-02T10:14:22Z',
    description: 'Immediately halts outbound wire dispatch if vendor registration age < 90 days, offshore non-FATF jurisdiction detected, or beneficiary IBAN modified in last 14 days.',
    accuracyScore: 98.4,
    createdBy: 'Dr. Elena Vance (ADMIN)',
    createdAt: '2025-11-15',
  },
  {
    id: 'rule_duplicate_invoice_02',
    name: 'Fuzzy Duplicate Invoice Hash Collision',
    code: 'RL-DUP-002',
    category: 'DUPLICATE_INVOICE',
    severity: 'HIGH',
    threshold: 'Exact Rupee Amount match within 14 days OR Levenshtein Inv# < 2',
    metric: 'InvoiceContentSimilarity',
    action: 'AUTO_QUARANTINE',
    enabled: true,
    triggerCount24h: 2,
    lastTriggered: '2026-04-02T09:30:11Z',
    description: 'Detects identical line items, sub-paisa invoice discrepancies, or resubmitted invoices under alternate PO numbers.',
    accuracyScore: 99.1,
    createdBy: 'Rajesh Malhotra (FINANCE_OFFICER)',
    createdAt: '2025-10-02',
  },
  {
    id: 'rule_smurfing_split_03',
    name: 'Sub-Threshold Split Invoice Sequence Watch',
    code: 'RL-SMF-003',
    category: 'SPLIT_TRANSACTION_SMURFING',
    severity: 'HIGH',
    threshold: '2+ invoices between ₹48,00,000 and ₹49,99,999 to same vendor in 48h',
    metric: 'ApprovalThresholdProximity',
    action: 'REQUIRE_DUAL_AUTH',
    enabled: true,
    triggerCount24h: 4,
    lastTriggered: '2026-04-02T08:12:45Z',
    description: 'Identifies potential invoice fragmentation designed to remain beneath the ₹50 Lakh executive dual-signatory threshold.',
    accuracyScore: 96.8,
    createdBy: 'Dr. Elena Vance (ADMIN)',
    createdAt: '2025-12-01',
  },
  {
    id: 'rule_off_hours_wire_04',
    name: 'Off-Hours High-Value Cross-Border Treasury Wire',
    code: 'RL-OFH-004',
    category: 'OFF_HOURS_TRANSFER',
    severity: 'CRITICAL',
    threshold: 'Amount > ₹1,00,00,000 (₹1 Cr) initiated between 22:00 - 05:00 IST',
    metric: 'TimestampAnomalyScore',
    action: 'AUTO_QUARANTINE',
    enabled: true,
    triggerCount24h: 1,
    lastTriggered: '2026-04-02T03:41:00Z',
    description: 'Flags treasury transfers executed during non-standard operating windows without cryptographic dual-token pre-approval.',
    accuracyScore: 97.2,
    createdBy: 'Dr. Elena Vance (ADMIN)',
    createdAt: '2025-09-18',
  },
  {
    id: 'rule_benford_law_05',
    name: "Benford's Law First-Digit Distribution Divergence",
    code: 'RL-BNF-005',
    category: 'BENFORD_ANOMALY',
    severity: 'MEDIUM',
    threshold: 'Chi-Square p-value < 0.01 across 30-day departmental ledger',
    metric: 'BenfordChiSquareScore',
    action: 'ALERT_FINANCE',
    enabled: true,
    triggerCount24h: 5,
    lastTriggered: '2026-04-02T07:22:19Z',
    description: 'Statistical surveillance of leading digits (1-9) in submitted receipts and invoices to detect non-random expense patterns.',
    accuracyScore: 92.5,
    createdBy: 'Rajesh Malhotra (FINANCE_OFFICER)',
    createdAt: '2026-01-10',
  },
  {
    id: 'rule_sanctions_pep_06',
    name: 'Regulatory Watchlist & PEP Realtime Screening',
    code: 'RL-SAN-006',
    category: 'SANCTIONS_MATCH',
    severity: 'CRITICAL',
    threshold: 'Entity name or beneficial owner similarity confidence > 85%',
    metric: 'WatchlistMatchConfidence',
    action: 'AUTO_QUARANTINE',
    enabled: true,
    triggerCount24h: 1,
    lastTriggered: '2026-04-02T04:15:00Z',
    description: 'Cross-checks all outbound beneficiaries against international trade restriction registries and politically exposed persons rosters.',
    accuracyScore: 99.8,
    createdBy: 'Dr. Elena Vance (ADMIN)',
    createdAt: '2025-08-01',
  },
  {
    id: 'rule_velocity_spike_07',
    name: 'Procurement Velocity Deviation (> 3.5σ Baseline)',
    code: 'RL-VEL-007',
    category: 'VELOCITY_SPIKE',
    severity: 'MEDIUM',
    threshold: 'Daily spend rate > 3.5 standard deviations from 90-day moving average',
    metric: 'VelocityZScore',
    action: 'ALERT_FINANCE',
    enabled: true,
    triggerCount24h: 3,
    lastTriggered: '2026-04-02T06:50:41Z',
    description: 'Flags sudden surges in departmental invoice submission frequency or aggregate daily volume spikes.',
    accuracyScore: 94.1,
    createdBy: 'Rajesh Malhotra (FINANCE_OFFICER)',
    createdAt: '2025-11-20',
  },
];
