import { Transaction } from '../types';

/**
 * FY 2026–27 Realistic Enterprise Transactions in INR (₹)
 * Uses objective, forensic anomaly classifications without premature fraud labeling.
 */
export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_snt_99481',
    referenceNo: 'TXN-2026-0402-99481',
    timestamp: '2026-04-02T10:14:22Z',
    fiscalYear: 'FY 2026–27',
    quarter: 'Q1',
    department: 'Finance & Treasury Management',
    departmentCode: 'FIN-04',
    vendorId: 'vnd_kestrel_holdings',
    vendorName: 'Kestrel Offshore Global Ventures SA',
    vendorCategory: 'Procurement Intermediary Agency',
    amount: 48500000, // ₹4.85 Crores
    currency: 'INR',
    category: 'Treasury Cross-Border Wire',
    status: 'QUARANTINED',
    riskScore: 97,
    riskLevel: 'CRITICAL',
    threatCategory: 'SANCTIONS_MATCH',
    threatFlags: [
      'Regulatory Watchlist Direct Match',
      'Bearer Share Jurisdiction (Panama)',
      'Sudden Outbound Wire Volume Surge',
      'Missing Corroborating Purchase Order',
    ],
    approver: 'Sentinel Automated Watchdog',
    paymentMethod: 'Fedwire / Swift MT103 Nostro',
    destinationAccount: 'PA88-BGPA-0091-2299-4401 (Banco General Panama)',
    originatingAccount: 'IN01-SENT-TREASURY-0992 (Corporate Treasury Node)',
    sha256Hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    aiForensicSummary:
      'High-risk anomalous wire transfer intercepted. Beneficiary entity Kestrel Offshore Global Ventures SA matches international regulatory watchlist screening criteria. Destination bank routing in non-FATF jurisdiction with zero verifiable trading history.',
    confidenceScore: 99.2,
    shapFactors: [
      {
        feature: 'Regulatory Watchlist Alignment',
        weight: 0.52,
        description: 'Beneficiary name matches high-risk entity watchlist record',
        value: '99.4% Match',
      },
      {
        feature: 'Offshore Routing Node',
        weight: 0.28,
        description: 'Panamanian non-cooperative financial banking jurisdiction',
        value: 'Panama (PA)',
      },
      {
        feature: 'Magnitude vs 90-Day Baseline',
        weight: 0.14,
        description: 'Single wire value exceeds median departmental allocation by 380%',
        value: '₹4,85,00,000.00 (₹4.85 Cr)',
      },
      {
        feature: 'Time-to-Execution Window',
        weight: 0.06,
        description: 'Rapid dispatch initiation without mandatory dual-officer ticket',
        value: '< 45 seconds',
      },
    ],
    auditTrail: [
      {
        id: 'aud_101',
        timestamp: '2026-04-02T10:14:22Z',
        actor: 'SENTINEL AI Engine v4.2',
        action: 'AUTOMATED_QUARANTINE_ENFORCED',
        details: 'Outbound wire message intercepted prior to clearing gateway transmission.',
        hash: 'a7c92b84e129f1b90c918237418293718923a4b9',
      },
      {
        id: 'aud_102',
        timestamp: '2026-04-02T10:15:00Z',
        actor: 'Rajesh Malhotra (FINANCE_OFFICER)',
        action: 'INTERNAL_FORENSIC_REVIEW_OPENED',
        details: 'Initiated Priority 1 Forensic Review Ticket #SAR-2026-081',
        hash: 'b8d91a92e109f2b81d827364519283746182c5d0',
      },
    ],
    forensicNotes: [
      'Treasury dual-authorization verification requested. Legal compliance team notified.',
      'Correspondent banking freeze status active pending internal audit clearance.',
    ],
    isFlaggedBySentinel: true,
  },
  {
    id: 'tx_snt_99480',
    referenceNo: 'TXN-2026-0402-99480',
    timestamp: '2026-04-02T09:30:11Z',
    fiscalYear: 'FY 2026–27',
    quarter: 'Q1',
    department: 'Engineering & Infrastructure',
    departmentCode: 'ENG-01',
    vendorId: 'vnd_cygnus_consulting',
    vendorName: 'Cygnus Strategic Advisory Solutions LLP',
    vendorCategory: 'Strategic IT & Management Consulting',
    amount: 4950000, // ₹49.50 Lakhs
    currency: 'INR',
    category: 'Technical Advisory Retainer',
    status: 'FLAGGED',
    riskScore: 91,
    riskLevel: 'CRITICAL',
    threatCategory: 'SPLIT_TRANSACTION_SMURFING',
    threatFlags: [
      'Sub-Threshold Split Invoice (< ₹50 Lakhs Cap)',
      'Recent IBAN Routing Alteration to Cyprus',
      'Unverified Shell Probability 84.6%',
      'Duplicate Scope Reference #ENG-4891',
    ],
    approver: 'Pending Forensic Clearance',
    paymentMethod: 'NEFT / Commercial RTGS',
    destinationAccount: 'CY14-HEBA-0012-9938-1102 (Cyprus)',
    originatingAccount: 'IN01-SENT-OPS-4410',
    sha256Hash: '4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945',
    aiForensicSummary:
      'Sub-threshold approval smurfing heuristic trigger. Transaction amount of ₹49,50,000 is engineered precisely ₹50,000 below the ₹50,00,000 dual-signatory executive authorization ceiling. Vendor modified beneficiary routing to Cyprus 11 days ago.',
    confidenceScore: 94.7,
    shapFactors: [
      {
        feature: 'Approval Ceiling Proximity',
        weight: 0.44,
        description: 'Amount is 99.0% of the ₹50 Lakh executive approval ceiling',
        value: '₹49,50,000 (Delta: ₹50,000)',
      },
      {
        feature: 'Beneficiary Routing Volatility',
        weight: 0.32,
        description: 'IBAN change from domestic bank to Cyprus within last 14 days',
        value: 'Altered 2026-03-18',
      },
      {
        feature: 'Invoice Text Duplication',
        weight: 0.18,
        description: 'Line items match prior invoice TXN-2026-0320-98311 by 97%',
        value: '97% Cosine Similarity',
      },
      {
        feature: 'Vendor Establishment Age',
        weight: 0.06,
        description: 'Vendor incorporated < 120 days ago',
        value: '118 days old',
      },
    ],
    auditTrail: [
      {
        id: 'aud_103',
        timestamp: '2026-04-02T09:30:11Z',
        actor: 'SENTINEL Heuristic Classifier',
        action: 'SMURFING_ANOMALY_TAGGED',
        details: 'Heuristic rules RL-SMF-003 and RL-PHN-001 fired synchronously.',
        hash: 'c9e01b83d119f3a72e938475629182736451d6e1',
      },
    ],
    forensicNotes: [
      'Contacted VP of Engineering Priya Sharma for invoice verification and milestone delivery proof.',
    ],
    isFlaggedBySentinel: true,
  },
  {
    id: 'tx_snt_99479',
    referenceNo: 'TXN-2026-0402-99479',
    timestamp: '2026-04-02T08:45:00Z',
    fiscalYear: 'FY 2026–27',
    quarter: 'Q1',
    department: 'Engineering & Infrastructure',
    departmentCode: 'ENG-01',
    vendorId: 'vnd_apex_cloud',
    vendorName: 'Apex HyperScale Cloud India Pvt Ltd',
    vendorCategory: 'Cloud Infrastructure & GPU Compute',
    amount: 18240000, // ₹1.82 Cr
    currency: 'INR',
    category: 'Cloud Infrastructure & GPU Compute',
    status: 'APPROVED',
    riskScore: 8,
    riskLevel: 'LOW',
    threatFlags: [],
    approver: 'Priya Sharma (VP Eng)',
    paymentMethod: 'Corporate Direct Bank Transfer',
    destinationAccount: 'HDFC-0004-9821-4412 (Bengaluru)',
    originatingAccount: 'IN01-SENT-OPS-4410',
    sha256Hash: '9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b',
    aiForensicSummary:
      'Standard recurring monthly cloud compute invoice. Matches contracted multi-year committed volume tier within expected 3% usage baseline variance.',
    confidenceScore: 98.6,
    shapFactors: [
      {
        feature: 'Vendor Reliability Scorecard',
        weight: -0.45,
        description: 'Verified Tier-1 Vendor with 42 consecutive clean billings',
        value: 'Score 12/100',
      },
      {
        feature: 'Historical Variance Band',
        weight: -0.35,
        description: 'Spend within +/- 2.8% of historical monthly mean',
        value: '+2.8% vs Mean',
      },
      {
        feature: '3-Way PO Reconciliation',
        weight: -0.20,
        description: 'Matched 3-way to Master Services Agreement #MSA-2024-881',
        value: 'Fully Matched',
      },
    ],
    auditTrail: [
      {
        id: 'aud_104',
        timestamp: '2026-04-02T08:45:00Z',
        actor: 'Auto-Reconciliation Engine',
        action: '3_WAY_MATCH_VERIFIED',
        details: 'Validated against ERP PO-99014 and Cloud Usage Meter API telemetry.',
        hash: 'd0f12c94e220a4b83f049586730293847562e7f2',
      },
    ],
    isFlaggedBySentinel: false,
  },
  {
    id: 'tx_snt_99478',
    referenceNo: 'TXN-2026-0402-99478',
    timestamp: '2026-04-02T03:41:00Z',
    fiscalYear: 'FY 2026–27',
    quarter: 'Q1',
    department: 'Finance & Treasury Management',
    departmentCode: 'FIN-04',
    vendorId: 'vnd_novatech_logistics',
    vendorName: 'NovaTech Supply Chain Solutions India',
    vendorCategory: 'Data Center Hardware & Logistics',
    amount: 14280000, // ₹1.43 Cr
    currency: 'INR',
    category: 'Hardware Procurement',
    status: 'QUARANTINED',
    riskScore: 88,
    riskLevel: 'HIGH',
    threatCategory: 'OFF_HOURS_TRANSFER',
    threatFlags: [
      'Off-Hours Execution (03:41 AM IST)',
      'PO Box Corporate Address Mismatch',
      'Single Signatory Bypass Trigger',
    ],
    approver: 'Sentinel Automated Watchdog',
    paymentMethod: 'Real-Time Gross Settlement (RTGS)',
    destinationAccount: 'UTIB-0000-8819-2234 (Gurugram)',
    originatingAccount: 'IN01-SENT-TREASURY-0992',
    sha256Hash: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
    aiForensicSummary:
      'Unscheduled high-value treasury transfer submitted at 03:41 AM IST. Registered address altered to an unverified commercial drop box in Nevada. Anomaly detected in payment schedule timing.',
    confidenceScore: 91.5,
    shapFactors: [
      {
        feature: 'Execution Timestamp Window',
        weight: 0.48,
        description: 'Submission occurred outside approved operational treasury trading window',
        value: '03:41 IST (Off-hours)',
      },
      {
        feature: 'Address Verification Score',
        weight: 0.28,
        description: 'Physical premise substituted with commercial drop-box',
        value: 'PO Box 88402',
      },
      {
        feature: 'Historical Cycle Timing',
        weight: 0.18,
        description: 'Vendor previously only billed bi-monthly on 15th',
        value: 'Out-of-cycle',
      },
    ],
    auditTrail: [
      {
        id: 'aud_105',
        timestamp: '2026-04-02T03:41:00Z',
        actor: 'SENTINEL Off-Hours Watchdog',
        action: 'QUARANTINE_ENFORCED',
        details: 'Transfer placed on hold pending morning dual-officer authorization.',
        hash: 'e1a23d05f331b5c94a150697841304958673f8a3',
      },
    ],
    forensicNotes: [
      'Operations supervisor contacted. Awaiting server delivery inspection sign-off.',
    ],
    isFlaggedBySentinel: true,
  },
  {
    id: 'tx_snt_99477',
    referenceNo: 'TXN-2026-0401-99477',
    timestamp: '2026-04-01T19:22:15Z',
    fiscalYear: 'FY 2026–27',
    quarter: 'Q1',
    department: 'Global Marketing & Brand Growth',
    departmentCode: 'MKT-02',
    vendorId: 'vnd_synergy_media',
    vendorName: 'Synergy Digital Media Networks LLP',
    vendorCategory: 'Performance Ad Exchange & Media Buy',
    amount: 7850000, // ₹78.50 Lakhs
    currency: 'INR',
    category: 'Digital Performance Media Campaigns',
    status: 'UNDER_REVIEW',
    riskScore: 68,
    riskLevel: 'MEDIUM',
    threatCategory: 'BENFORD_ANOMALY',
    threatFlags: [
      'Benford Leading Digit Frequency Anomaly',
      'Media Delivery Impression Disconnect',
      'Unusual Round Number Clustering',
    ],
    approver: 'Julian Vance (Marketing Head)',
    paymentMethod: 'Corporate Virtual Card Gateway',
    destinationAccount: 'KKBK-0001-1102-4491 (New Delhi)',
    originatingAccount: 'IN01-SENT-MKT-8821',
    sha256Hash: '5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f',
    aiForensicSummary:
      "Marketing media billing demonstrates abnormal clustering around digits 7 and 8, showing statistically significant divergence from Benford's first-digit distribution. Third-party pixel attribution telemetry is undergoing reconciliation.",
    confidenceScore: 84.2,
    shapFactors: [
      {
        feature: 'Benford Chi-Square Test',
        weight: 0.38,
        description: 'Digit distribution deviates from natural logarithmic curve',
        value: 'p = 0.0041',
      },
      {
        feature: 'Conversion Telemetry Match',
        weight: 0.32,
        description: 'Media invoice lacks corresponding ad server API pixel telemetry',
        value: 'Unverified Pixel',
      },
      {
        feature: 'Sequential Digit Repetition',
        weight: 0.20,
        description: 'Similar rounded numbers billed across consecutive billing runs',
        value: '₹78,50,000 / ₹78,40,000',
      },
    ],
    auditTrail: [
      {
        id: 'aud_106',
        timestamp: '2026-04-01T19:22:15Z',
        actor: 'SENTINEL Statistical Analyzer',
        action: 'BENFORD_FLAG_RAISED',
        details: 'Routed to Julian Vance for marketing attribution verification.',
        hash: 'f2b34e16a442c6d05b261708952415069784a9b4',
      },
    ],
    isFlaggedBySentinel: true,
  },
  {
    id: 'tx_snt_99476',
    referenceNo: 'TXN-2026-0401-99476',
    timestamp: '2026-04-01T16:11:04Z',
    fiscalYear: 'FY 2026–27',
    quarter: 'Q1',
    department: 'Cybersecurity & Internal Controls',
    departmentCode: 'SEC-05',
    vendorId: 'vnd_vanguard_security',
    vendorName: 'Vanguard Cyber Threat Defense Ltd',
    vendorCategory: 'Enterprise Security Software & SOC Feeds',
    amount: 11250000, // ₹1.13 Cr
    currency: 'INR',
    category: 'Annual SOC Defense License Renewal',
    status: 'APPROVED',
    riskScore: 14,
    riskLevel: 'LOW',
    threatFlags: [],
    approver: 'Dr. Elena Vance (ADMIN)',
    paymentMethod: 'International Commercial Wire',
    destinationAccount: 'GB29-BARC-2000-0012-9844-01 (Barclays London)',
    originatingAccount: 'IN01-SENT-SEC-1109',
    sha256Hash: '2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c',
    aiForensicSummary:
      'Annual enterprise threat intelligence subscription renewal. Fully matched to signed vendor MSA with certified UK Barclays recipient.',
    confidenceScore: 99.4,
    shapFactors: [
      {
        feature: 'Authorized Executive Signature',
        weight: -0.50,
        description: 'Approved directly by Chief Risk & Information Security Officer',
        value: 'Dr. Elena Vance',
      },
      {
        feature: 'Contractual Milestone Match',
        weight: -0.30,
        description: 'Matched schedule to SOC defense annual commitment',
        value: 'Schedule A-1',
      },
    ],
    auditTrail: [
      {
        id: 'aud_107',
        timestamp: '2026-04-01T16:11:04Z',
        actor: 'Dr. Elena Vance (ADMIN)',
        action: 'MANUAL_APPROVAL_RECORDED',
        details: 'Approved quarterly SOC license renewal payment.',
        hash: 'a3c45f27b553d7e16c372819063526170895b0c5',
      },
    ],
    isFlaggedBySentinel: false,
  },
  {
    id: 'tx_snt_99475',
    referenceNo: 'TXN-2026-0401-99475',
    timestamp: '2026-04-01T14:05:32Z',
    fiscalYear: 'FY 2026–27',
    quarter: 'Q1',
    department: 'People Operations & Talent Acquisition',
    departmentCode: 'HR-06',
    vendorId: 'vnd_nexus_staffing',
    vendorName: 'Nexus Talent Solutions India Pvt Ltd',
    vendorCategory: 'Technical Recruiting & Staffing Advisory',
    amount: 3200000, // ₹32 Lakhs
    currency: 'INR',
    category: 'Executive Search Retainer',
    status: 'APPROVED',
    riskScore: 19,
    riskLevel: 'LOW',
    threatFlags: [],
    approver: 'Amara Okafor (HR Head)',
    paymentMethod: 'NEFT Commercial Direct',
    destinationAccount: 'SBIN-0004-4491-0012 (Pune)',
    originatingAccount: 'IN01-SENT-HR-7712',
    sha256Hash: '3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d',
    aiForensicSummary:
      'Standard recruiter fee for successfully onboarded Staff AI Infrastructure Lead. Verified against HRIS ledger and background check records.',
    confidenceScore: 97.5,
    shapFactors: [
      {
        feature: 'Employee Active Status Verification',
        weight: -0.40,
        description: 'Employee ID verified active in HRMS system',
        value: 'Emp #ENG-184',
      },
      {
        feature: 'Fee Rate Compliance',
        weight: -0.35,
        description: 'Fee percentage matches contracted standard terms',
        value: 'Standard Term',
      },
    ],
    auditTrail: [
      {
        id: 'aud_108',
        timestamp: '2026-04-01T14:05:32Z',
        actor: 'Amara Okafor (HR Head)',
        action: 'HR_PAYMENT_RELEASED',
        details: 'Staff recruitment fee verified.',
        hash: 'b4d56a38c664e8f27d483920174637281906c1d6',
      },
    ],
    isFlaggedBySentinel: false,
  },
  {
    id: 'tx_snt_99474',
    referenceNo: 'TXN-2026-0331-99474',
    timestamp: '2026-03-31T18:50:19Z',
    fiscalYear: 'FY 2026–27',
    quarter: 'Q1',
    department: 'Engineering & Infrastructure',
    departmentCode: 'ENG-01',
    vendorId: 'vnd_quantum_ai_labs',
    vendorName: 'QuantumAI Research Systems India Pvt Ltd',
    vendorCategory: 'AI Model Weights & Financial Dataset Feeds',
    amount: 9800000, // ₹98 Lakhs
    currency: 'INR',
    category: 'AI Domain Dataset Licenses & Model Tuning',
    status: 'APPROVED',
    riskScore: 21,
    riskLevel: 'LOW',
    threatFlags: [],
    approver: 'Priya Sharma (VP Eng)',
    paymentMethod: 'RTGS Corporate Bank Transfer',
    destinationAccount: 'ICIC-0004-4491-0029 (Hyderabad)',
    originatingAccount: 'IN01-SENT-OPS-4410',
    sha256Hash: '4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e',
    aiForensicSummary:
      'Quarterly licensing payment for specialized financial domain model fine-tuning weights and verified market dataset feeds.',
    confidenceScore: 96.8,
    shapFactors: [
      {
        feature: 'SLA Delivery Verification',
        weight: -0.40,
        description: 'Dataset hash verified on secure enterprise repository',
        value: 'SHA256 Match',
      },
    ],
    auditTrail: [
      {
        id: 'aud_109',
        timestamp: '2026-03-31T18:50:19Z',
        actor: 'Priya Sharma (VP Eng)',
        action: 'INVOICE_APPROVED',
        details: 'Verified dataset delivery with machine learning engineering team.',
        hash: 'c5e67b49d775f9a38e594031285748392017d2e7',
      },
    ],
    isFlaggedBySentinel: false,
  },
  {
    id: 'tx_snt_99473',
    referenceNo: 'TXN-2026-0331-99473',
    timestamp: '2026-03-31T11:28:44Z',
    fiscalYear: 'FY 2026–27',
    quarter: 'Q1',
    department: 'Corporate Operations & Logistics',
    departmentCode: 'OPS-03',
    vendorId: 'vnd_novatech_logistics',
    vendorName: 'NovaTech Supply Chain Solutions India',
    vendorCategory: 'Data Center Hardware & Logistics',
    amount: 5410000, // ₹54.10 Lakhs
    currency: 'INR',
    category: 'Data Center Rack Cooling Systems',
    status: 'FLAGGED',
    riskScore: 78,
    riskLevel: 'HIGH',
    threatCategory: 'DUPLICATE_INVOICE',
    threatFlags: [
      'Duplicate Serial Number #RACK-COOL-882',
      'Invoice Line Item Match to PO-4109',
      'Short-Cycle Resubmission Pattern',
    ],
    approver: 'Vikram Seth (Ops Head)',
    paymentMethod: 'Commercial RTGS Transfer',
    destinationAccount: 'UTIB-0000-8819-2234 (Gurugram)',
    originatingAccount: 'IN01-SENT-OPS-4410',
    sha256Hash: '5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f',
    aiForensicSummary:
      'Optical Character Recognition (OCR) and semantic analysis detected 99.4% identical bill of materials to invoice cleared on 2026-01-30. Hardware equipment serial numbers duplicate prior registry.',
    confidenceScore: 93.1,
    shapFactors: [
      {
        feature: 'Serial Number Collision',
        weight: 0.55,
        description: 'Hardware equipment serial numbers previously billed and cleared',
        value: 'Exact Duplicate',
      },
      {
        feature: 'Amount Similarity',
        weight: 0.25,
        description: 'Exact rupee figure matching previous month transaction',
        value: '₹54,10,000 Exact',
      },
    ],
    auditTrail: [
      {
        id: 'aud_110',
        timestamp: '2026-03-31T11:28:44Z',
        actor: 'SENTINEL OCR Pipeline',
        action: 'DUPLICATE_INVOICE_INTERCEPTED',
        details: 'Serial number collision matched against physical asset registry.',
        hash: 'd6f78c50e886a0b49f605142396859403128e3f8',
      },
    ],
    forensicNotes: [
      'Vikram Seth notified to conduct physical data center warehouse verification.',
    ],
    isFlaggedBySentinel: true,
  },
  {
    id: 'tx_snt_99472',
    referenceNo: 'TXN-2026-0330-99472',
    timestamp: '2026-03-30T15:19:08Z',
    fiscalYear: 'FY 2026–27',
    quarter: 'Q1',
    department: 'Global Marketing & Brand Growth',
    departmentCode: 'MKT-02',
    vendorId: 'vnd_synergy_media',
    vendorName: 'Synergy Digital Media Networks LLP',
    vendorCategory: 'Performance Ad Exchange & Media Buy',
    amount: 12500000, // ₹1.25 Cr
    currency: 'INR',
    category: 'Q1 Global Fintech Conference Sponsorship',
    status: 'APPROVED',
    riskScore: 28,
    riskLevel: 'LOW',
    threatFlags: [],
    approver: 'Julian Vance (Marketing Head)',
    paymentMethod: 'Commercial RTGS Transfer',
    destinationAccount: 'KKBK-0001-1102-4491 (New Delhi)',
    originatingAccount: 'IN01-SENT-MKT-8821',
    sha256Hash: '6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a',
    aiForensicSummary:
      'Scheduled quarterly fintech industry conference sponsorship payment. Executed under pre-cleared annual marketing agency contract.',
    confidenceScore: 95.0,
    shapFactors: [
      {
        feature: 'Contractual Reference Verification',
        weight: -0.45,
        description: 'Verified against Master Sponsorship Agreement',
        value: 'Verified MSA',
      },
    ],
    auditTrail: [
      {
        id: 'aud_111',
        timestamp: '2026-03-30T15:19:08Z',
        actor: 'Julian Vance (Marketing Head)',
        action: 'PAYMENT_AUTHORIZED',
        details: 'Conference sponsorship contract countersigned.',
        hash: 'e7a89d61f997b1c50a716253407960514239f4a9',
      },
    ],
    isFlaggedBySentinel: false,
  },
];
