import { User } from '../types';

export const DEMO_USERS: User[] = [
  {
    id: 'usr_admin_01',
    name: 'Dr. Elena Vance',
    email: 'elena.vance@sentinel-fin.internal',
    role: 'ADMIN',
    roleTitle: 'Chief Risk & Information Security Officer',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    permissions: {
      canManageRules: true,
      canQuarantineTransactions: true,
      canApproveBudgets: true,
      canExportForensics: true,
      canManageUsers: true,
      canRunSimulations: true,
      canGenerateSAR: true,
    },
    lastLogin: '2026-04-02T08:42:15Z',
    twoFactorEnabled: true,
  },
  {
    id: 'usr_finance_02',
    name: 'Rajesh Malhotra',
    email: 'rajesh.malhotra@sentinel-fin.internal',
    role: 'FINANCE_OFFICER',
    roleTitle: 'Senior Financial Controller & Treasury Lead',
    department: 'Corporate Treasury & Internal Controls',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    permissions: {
      canManageRules: false,
      canQuarantineTransactions: true,
      canApproveBudgets: true,
      canExportForensics: true,
      canManageUsers: false,
      canRunSimulations: true,
      canGenerateSAR: true,
    },
    lastLogin: '2026-04-02T09:14:02Z',
    twoFactorEnabled: true,
  },
  {
    id: 'usr_dept_03',
    name: 'Priya Sharma',
    email: 'priya.sharma@sentinel-fin.internal',
    role: 'DEPARTMENT_HEAD',
    roleTitle: 'VP of Engineering & Technology Head',
    department: 'Engineering & Technology',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    permissions: {
      canManageRules: false,
      canQuarantineTransactions: false,
      canApproveBudgets: false,
      canExportForensics: true,
      canManageUsers: false,
      canRunSimulations: false,
      canGenerateSAR: false,
    },
    lastLogin: '2026-04-02T10:05:33Z',
    twoFactorEnabled: false,
  },
];
