import { VendorIntelligence } from '../types';

export const INITIAL_VENDORS: VendorIntelligence[] = [
  {
    id: 'vnd_apex_cloud',
    name: 'Apex HyperScale Cloud India Pvt Ltd',
    taxId: 'GSTIN: 29AAACA8821K1Z5',
    category: 'Cloud Infrastructure & GPU Compute',
    riskScore: 12,
    riskLevel: 'LOW',
    status: 'VERIFIED',
    totalVolumeYTD: 54200000, // ₹5.42 Cr
    invoiceCount: 42,
    flaggedInvoicesCount: 0,
    bankAccount: 'HDFC-0004-9821-4412 (Bengaluru Koramangala)',
    bankName: 'HDFC Bank Ltd',
    jurisdiction: 'India (Karnataka / Delaware Parent)',
    ghostCompanyProbability: 0.8,
    sanctionsCheckStatus: 'CLEARED',
    pepMatch: false,
    lastAuditDate: '2026-02-15',
    incorporationDate: '2016-04-12',
    recentAlterations: [],
  },
  {
    id: 'vnd_cygnus_consulting',
    name: 'Cygnus Strategic Advisory Solutions LLP',
    taxId: 'PAN: AABCC9921D / GSTIN: 27AABCC9921D1ZQ',
    category: 'Strategic IT & Management Consulting',
    riskScore: 89,
    riskLevel: 'CRITICAL',
    status: 'FLAGGED',
    totalVolumeYTD: 8900000, // ₹89 Lakhs
    invoiceCount: 7,
    flaggedInvoicesCount: 4,
    bankAccount: 'CY14-HEBA-0012-9938-1102 (Nicosia Overseas Branch)',
    bankName: 'Hellenic Bank Nicosia',
    jurisdiction: 'Cyprus (Offshore Corporate Registry)',
    ghostCompanyProbability: 84.6,
    sanctionsCheckStatus: 'POTENTIAL_MATCH',
    pepMatch: true,
    lastAuditDate: '2026-03-20',
    incorporationDate: '2025-11-03',
    recentAlterations: [
      {
        date: '2026-03-18',
        field: 'Beneficiary Routing & Overseas IBAN',
        oldValue: 'ICIC0001092 (Mumbai Nariman Point)',
        newValue: 'CY14-HEBA-0012-9938-1102 (Cyprus)',
        flagged: true,
      },
      {
        date: '2026-03-10',
        field: 'Authorized Board Signatory',
        oldValue: 'R. Sterling',
        newValue: 'K. Rostova (Nominee Director)',
        flagged: true,
      },
    ],
  },
  {
    id: 'vnd_novatech_logistics',
    name: 'NovaTech Supply Chain Solutions India',
    taxId: 'GSTIN: 06AABCN8819E1ZM',
    category: 'Data Center Hardware & Logistics',
    riskScore: 76,
    riskLevel: 'HIGH',
    status: 'WATCHLIST',
    totalVolumeYTD: 14200000, // ₹1.42 Cr
    invoiceCount: 16,
    flaggedInvoicesCount: 3,
    bankAccount: 'UTIB-0000-8819-2234 (Gurugram CyberHub)',
    bankName: 'Axis Bank Ltd',
    jurisdiction: 'India (Haryana / Nevada Sub)',
    ghostCompanyProbability: 42.1,
    sanctionsCheckStatus: 'CLEARED',
    pepMatch: false,
    lastAuditDate: '2026-03-05',
    incorporationDate: '2024-08-19',
    recentAlterations: [
      {
        date: '2026-03-01',
        field: 'Corporate Billing Address',
        oldValue: 'Golf Course Road, Gurugram, HR',
        newValue: 'PO BOX 88402, Reno, Nevada (Drop Box)',
        flagged: true,
      },
    ],
  },
  {
    id: 'vnd_quantum_ai_labs',
    name: 'QuantumAI Research Systems India Pvt Ltd',
    taxId: 'GSTIN: 36AABCQ3948F1ZX',
    category: 'AI Model Weights & Financial Dataset Feeds',
    riskScore: 24,
    riskLevel: 'LOW',
    status: 'VERIFIED',
    totalVolumeYTD: 21500000, // ₹2.15 Cr
    invoiceCount: 18,
    flaggedInvoicesCount: 0,
    bankAccount: 'ICIC-0004-4491-0029 (Hyderabad HITEC City)',
    bankName: 'ICICI Bank Ltd',
    jurisdiction: 'India (Telangana / Massachusetts)',
    ghostCompanyProbability: 2.3,
    sanctionsCheckStatus: 'CLEARED',
    pepMatch: false,
    lastAuditDate: '2026-02-28',
    incorporationDate: '2019-02-14',
    recentAlterations: [],
  },
  {
    id: 'vnd_vanguard_security',
    name: 'Vanguard Cyber Threat Defense Ltd',
    taxId: 'GB-VAT-992-1847-20 / IEC: 0519284102',
    category: 'Enterprise Security Software & SOC Feeds',
    riskScore: 18,
    riskLevel: 'LOW',
    status: 'VERIFIED',
    totalVolumeYTD: 13500000, // ₹1.35 Cr
    invoiceCount: 12,
    flaggedInvoicesCount: 0,
    bankAccount: 'GB29-BARC-2000-0012-9844-01 (Barclays London)',
    bankName: 'Barclays Bank PLC',
    jurisdiction: 'United Kingdom (London)',
    ghostCompanyProbability: 1.1,
    sanctionsCheckStatus: 'CLEARED',
    pepMatch: false,
    lastAuditDate: '2026-02-10',
    incorporationDate: '2015-09-22',
    recentAlterations: [],
  },
  {
    id: 'vnd_kestrel_holdings',
    name: 'Kestrel Offshore Global Ventures SA',
    taxId: 'PA-RUC-8849201 / Unverified FII',
    category: 'Procurement Intermediary Agency',
    riskScore: 94,
    riskLevel: 'CRITICAL',
    status: 'SUSPENDED',
    totalVolumeYTD: 18200000, // ₹1.82 Cr
    invoiceCount: 5,
    flaggedInvoicesCount: 5,
    bankAccount: 'PA88-BGPA-0091-2299-4401 (Banco General Panama)',
    bankName: 'Banco General Panama',
    jurisdiction: 'Panama (Bearer Share Holding Structure)',
    ghostCompanyProbability: 93.8,
    sanctionsCheckStatus: 'SANCTIONED',
    pepMatch: true,
    lastAuditDate: '2026-03-28',
    incorporationDate: '2025-12-18',
    recentAlterations: [
      {
        date: '2026-03-25',
        field: 'Tax Compliance ID',
        oldValue: 'Pending Documentation',
        newValue: 'RUC-8849201 (Unverified Entity)',
        flagged: true,
      },
    ],
  },
  {
    id: 'vnd_synergy_media',
    name: 'Synergy Digital Media Networks LLP',
    taxId: 'GSTIN: 07AABCS9988H1ZP',
    category: 'Performance Ad Exchange & Media Buy',
    riskScore: 48,
    riskLevel: 'MEDIUM',
    status: 'WATCHLIST',
    totalVolumeYTD: 9200000, // ₹92 Lakhs
    invoiceCount: 14,
    flaggedInvoicesCount: 2,
    bankAccount: 'KKBK-0001-1102-4491 (New Delhi Connaught Place)',
    bankName: 'Kotak Mahindra Bank',
    jurisdiction: 'India (Delhi NCR)',
    ghostCompanyProbability: 18.4,
    sanctionsCheckStatus: 'CLEARED',
    pepMatch: false,
    lastAuditDate: '2026-03-12',
    incorporationDate: '2021-06-30',
    recentAlterations: [],
  },
  {
    id: 'vnd_nexus_staffing',
    name: 'Nexus Talent Solutions India Pvt Ltd',
    taxId: 'GSTIN: 27AABCN3388J1ZR',
    category: 'Technical Recruiting & Staffing Advisory',
    riskScore: 32,
    riskLevel: 'LOW',
    status: 'VERIFIED',
    totalVolumeYTD: 6400000, // ₹64 Lakhs
    invoiceCount: 11,
    flaggedInvoicesCount: 0,
    bankAccount: 'SBIN-0004-4491-0012 (Pune Shivaji Nagar)',
    bankName: 'State Bank of India',
    jurisdiction: 'India (Maharashtra)',
    ghostCompanyProbability: 5.2,
    sanctionsCheckStatus: 'CLEARED',
    pepMatch: false,
    lastAuditDate: '2026-02-20',
    incorporationDate: '2018-11-05',
    recentAlterations: [],
  },
];
